### ISSUE TITLE
Binaries unavailable

### ISSUE THREAD

**Issue by wkejqb** [kparc/k#20]
Hi,
https://anaconda.org/shaktidb/shakti/files :  `You don't have permission to view this page.`
Therefore, installer does not work.

**Comment by sternenseemann** [comment]
New URL seems to be

* <https://shakti.com/linux/k.zip>
* <https://shakti.com/macos/k.zip>

They seem to be trying to prevent automatic downloads: The URLs only work, if you sign up at <https://shakti.com/download/> beforehand, otherwise they return 404. Not sure, if you can trick the web server somehow.

**Comment by wkejqb** [comment]
Thanks!

**Comment by sternenseemann** [comment]
Feel free to reopen, still a problem for this installation utility…
